# Generated by Django 5.2.6 on 2025-10-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customprofiles_is_social_customprofiles_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofiles',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
